name: Build docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and push Docker image to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Generate version number
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: version
        run: |
          base_version=$(grep "version =" pyproject.toml | awk -F'"' '{print $2}' | awk -F'.' '{print $1"."$2}')
          last_tag=$(git describe --tags --abbrev=0 --match "v${base_version}.*" 2>/dev/null || echo "v${base_version}.0")
          build_number=$(echo $last_tag | awk -F'.' '{print $NF}')
          build_number=$((build_number + 1))
          full_version="${base_version}.${build_number}"
          echo "full_version=${full_version}" >> $GITHUB_OUTPUT
          echo "Full version: ${full_version}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.CI_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create ECR Repository if it doesn't exist
        run: |
          aws ecr describe-repositories --repository-names speech-audio-quality-containers \
            || aws ecr create-repository --repository-name speech-audio-quality-containers

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0
        with:
          install: true

      - name: Build and push Docker image
        if: github.event_name != 'workflow_dispatch'
        uses: docker/build-push-action@v6.3.0
        with:
          context: .
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/mlunflow:${{ steps.version.outputs.full_version }}
            ${{ steps.login-ecr.outputs.registry }}/mlunflow:latest
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secrets: |
            token-gen-app-id: ${{ secrets.ARC_GITHUB_CI_TOKEN_GEN_APP_ID }}
            token-gen-private-key: ${{ secrets.ARC_GITHUB_CI_TOKEN_GEN_KEY }}

      - name: Build and push Docker image
        if: github.event_name == 'workflow_dispatch'
        uses: docker/build-push-action@v6.3.0
        with:
          context: .
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/mlunflow:${{ env.LAST_COMMIT }}:${{ github.ref_name }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secrets: |
            token-gen-app-id: ${{ secrets.ARC_GITHUB_CI_TOKEN_GEN_APP_ID }}
            token-gen-private-key: ${{ secrets.ARC_GITHUB_CI_TOKEN_GEN_KEY }}

      - name: Create Git Tag
        if: github.event_name != 'workflow_dispatch'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -a v${{ steps.version.outputs.full_version }} -m "Release ${{ steps.version.outputs.full_version }}"
          git push origin v${{ steps.version.outputs.full_version }}